# =============================================================================
# Tests for KitaevHoneycomb matter-sector finite-temperature observables.
#
# Implementation: KitaevHoneycomb_thermal.jl evaluates the matter-Majorana
# free-fermion partition function generated by the flux-free-sector Bloch
# Hamiltonian (`λ_k = |f(k)|`).  The Z₂ flux degrees of freedom are *not*
# thermalised — this is the standard matter-sector approximation, valid
# for `T ≪ Δ_v` (`Δ_v ≈ 0.07 |K|` at the isotropic gapless point; larger
# in the gapped A-phases).
#
# Layers:
#   1. T → 0 (β=80) consistency: thermal observables match GS values from
#      `KitaevHoneycomb.jl`.
#   2. T → ∞ (β=1e-4) analytic limits: matter sector is one Majorana mode
#      per unit cell (= 1 fermion mode per 2 sites), so the per-site
#      entropy saturates at log(2)/2 ≈ 0.34657...
#   3. Thermodynamic identities (ε = f + T·s, c_v = -β² ∂ε/∂β via
#      ForwardDiff) at gapless isotropic point — both Infinite and OBC.
#   4. OBC → Infinite convergence: per-site free energy converges as
#      Lx = Ly grow (gapless point ⇒ algebraic boundary effects).
#   5. Phase smoke test: c_v finite & positive in both gapless (B-phase)
#      and gapped (A_z) parameter regimes.
# =============================================================================

using QAtlas
using QAtlas:
    KitaevHoneycomb, Energy, FreeEnergy, ThermalEntropy, SpecificHeat, OBC, Infinite
using Test
using LinearAlgebra
using ForwardDiff

@testset "KitaevHoneycomb matter-sector thermal observables" begin

    # ───────────────────────────────────────────────────────────────────────
    # Layer 1: T → 0 consistency (β large).
    #
    # The thermal formulas use the convention `Z = ∏ 2 cosh(β λ_k / 2)`
    # (single-fermion levels at `±λ_k/2`), which gives a per-site GS
    # of `-Σ λ_k / (4 Lx Ly)` (Infinite: `-(1/(2·(2π)²))·∫(λ/2)d²θ`).
    # The thermal and GS paths share the *same* matter-Majorana
    # convention: single complex-fermion levels at `±σ_k`, giving
    # `Z_k = 2 cosh(βσ_k)` and `ε(β→∞) = -Σ σ_k / N_sites` per site,
    # which exactly matches the GS routine's `-Σ σ_k / (2 Lx Ly)`.
    # ───────────────────────────────────────────────────────────────────────
    @testset "T → 0 consistency (β=80)" begin
        m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        β_low = 80.0

        # Self-consistency: ε_thermal(β=80) ≈ f_thermal(β=80) (entropy
        # term is small).  Both Infinite and OBC.
        ε_th_inf = QAtlas.fetch(m, Energy(:per_site), Infinite(); beta=β_low)
        f_th_inf = QAtlas.fetch(m, FreeEnergy(), Infinite(); beta=β_low)
        @test ε_th_inf ≈ f_th_inf rtol = 1e-2

        ε_th_obc = QAtlas.fetch(m, Energy(:per_site), OBC(0); Lx=4, Ly=4, beta=β_low)
        f_th_obc = QAtlas.fetch(m, FreeEnergy(), OBC(0); Lx=4, Ly=4, beta=β_low)
        @test ε_th_obc ≈ f_th_obc rtol = 1e-2

        # Cross-validation against GS routine — must agree at large β
        # (entropy correction `O(exp(-β Δ))` for the gapped phase, only
        # algebraic at the gapless isotropic point so we use a loose
        # rtol = 1e-3).
        ε_gs_inf = QAtlas.fetch(m, Energy(), Infinite())
        @test ε_th_inf ≈ ε_gs_inf rtol = 1e-3
        ε_gs_obc = QAtlas.fetch(m, Energy(), OBC(0); Lx=4, Ly=4)
        @test ε_th_obc ≈ ε_gs_obc rtol = 1e-3

        # Gapless point: Dirac modes give algebraic decay of s, c_v.
        # Loose bounds (still tiny vs O(1) high-T values).
        s_inf = QAtlas.fetch(m, ThermalEntropy(), Infinite(); beta=β_low)
        @test abs(s_inf) < 1e-3
        c_inf = QAtlas.fetch(m, SpecificHeat(), Infinite(); beta=β_low)
        @test abs(c_inf) < 1e-3

        # Gapped Az phase: all λ_k ≥ Δ = 2(Kz - Kx - Ky) > 0, so
        # entropy / specific heat vanish exponentially.  This works
        # regardless of the convention factor of 2.
        m_gapped = KitaevHoneycomb(; Kx=0.5, Ky=0.5, Kz=2.0)
        s_inf_g = QAtlas.fetch(m_gapped, ThermalEntropy(), Infinite(); beta=β_low)
        @test abs(s_inf_g) < 1e-10
        c_inf_g = QAtlas.fetch(m_gapped, SpecificHeat(), Infinite(); beta=β_low)
        @test abs(c_inf_g) < 1e-10
        s_obc_g = QAtlas.fetch(m_gapped, ThermalEntropy(), OBC(0); Lx=4, Ly=4, beta=β_low)
        @test abs(s_obc_g) < 1e-10
        c_obc_g = QAtlas.fetch(m_gapped, SpecificHeat(), OBC(0); Lx=4, Ly=4, beta=β_low)
        @test abs(c_obc_g) < 1e-10
    end

    # ───────────────────────────────────────────────────────────────────────
    # Layer 2: T → ∞ analytic limits.
    #
    # Matter sector has Lx·Ly modes per Lx·Ly unit cells (= N_sites/2 modes
    # in total), each contributing log(2) of entropy at infinite T.  Per-site
    # entropy thus saturates at log(2)/2.  c_v vanishes ∝ β² as the modes
    # decouple from the thermal bath.
    # ───────────────────────────────────────────────────────────────────────
    @testset "T → ∞ analytic limits (β=1e-4)" begin
        m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        β_high = 1e-4

        # Per-site entropy → log(2)/2
        s_inf = QAtlas.fetch(m, ThermalEntropy(), Infinite(); beta=β_high)
        @test s_inf ≈ log(2) / 2 atol = 1e-6

        s_obc = QAtlas.fetch(m, ThermalEntropy(), OBC(0); Lx=4, Ly=4, beta=β_high)
        @test s_obc ≈ log(2) / 2 atol = 1e-6

        # Free energy per site at β → 0:  f → -T · log(2)/2
        f_inf = QAtlas.fetch(m, FreeEnergy(), Infinite(); beta=β_high)
        @test f_inf ≈ -log(2) / (2 * β_high) atol = 1e-3 / β_high

        # Specific heat → 0 at β → 0 (quadratic in β)
        c_inf = QAtlas.fetch(m, SpecificHeat(), Infinite(); beta=β_high)
        @test abs(c_inf) < 1e-6
        c_obc = QAtlas.fetch(m, SpecificHeat(), OBC(0); Lx=4, Ly=4, beta=β_high)
        @test abs(c_obc) < 1e-6
    end

    # ───────────────────────────────────────────────────────────────────────
    # Layer 3: Thermodynamic identities at the gapless isotropic point.
    # Hand-rolled identity check (the harness in
    # `test/util/thermodynamic_identities.jl` reads `bc.N` for OBC, but
    # KitaevHoneycomb OBC takes `Lx, Ly` kwargs instead).
    # ───────────────────────────────────────────────────────────────────────
    @testset "thermodynamic identities (Infinite)" begin
        m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        for β in (0.5, 1.0, 2.0)
            ε = QAtlas.fetch(m, Energy(:per_site), Infinite(); beta=β)
            f = QAtlas.fetch(m, FreeEnergy(), Infinite(); beta=β)
            s = QAtlas.fetch(m, ThermalEntropy(), Infinite(); beta=β)
            @test ε ≈ f + s / β atol = 1e-9

            dε = ForwardDiff.derivative(
                b -> QAtlas.fetch(m, Energy(:per_site), Infinite(); beta=b), β
            )
            c = QAtlas.fetch(m, SpecificHeat(), Infinite(); beta=β)
            @test c ≈ -β^2 * dε rtol = 1e-3
        end
    end

    @testset "thermodynamic identities (OBC 4×4)" begin
        m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        Lx, Ly = 4, 4
        for β in (0.5, 1.0, 2.0)
            ε = QAtlas.fetch(m, Energy(:per_site), OBC(0); Lx=Lx, Ly=Ly, beta=β)
            f = QAtlas.fetch(m, FreeEnergy(), OBC(0); Lx=Lx, Ly=Ly, beta=β)
            s = QAtlas.fetch(m, ThermalEntropy(), OBC(0); Lx=Lx, Ly=Ly, beta=β)
            @test ε ≈ f + s / β atol = 1e-9

            dε = ForwardDiff.derivative(
                b -> QAtlas.fetch(m, Energy(:per_site), OBC(0); Lx=Lx, Ly=Ly, beta=b), β
            )
            c = QAtlas.fetch(m, SpecificHeat(), OBC(0); Lx=Lx, Ly=Ly, beta=β)
            @test c ≈ -β^2 * dε rtol = 1e-3
        end
    end

    # ───────────────────────────────────────────────────────────────────────
    # Layer 4: OBC → Infinite convergence (Lx = Ly grows, β fixed).
    # The gapless isotropic point has algebraic boundary effects, so
    # convergence is slower than the gapped TFIM disordered phase.
    # ───────────────────────────────────────────────────────────────────────
    @testset "OBC → Infinite convergence (gapless isotropic)" begin
        m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        β = 1.0
        f_inf = QAtlas.fetch(m, FreeEnergy(), Infinite(); beta=β)
        Ls = (4, 8, 16)
        errs = Float64[]
        for L in Ls
            f_obc = QAtlas.fetch(m, FreeEnergy(), OBC(0); Lx=L, Ly=L, beta=β)
            push!(errs, abs(f_obc - f_inf))
        end
        # Largest box: |Δf| < 3e-2 — gapless point has algebraic
        # (not exponential) boundary effects in 2D; 16×16 still leaves
        # a measurable residual.  This is well below |f_inf| ≈ 1.
        @test errs[end] < 3e-2
        # Convergence: 16×16 error strictly smaller than 4×4 error.
        @test errs[end] < errs[1]
    end

    # ───────────────────────────────────────────────────────────────────────
    # Layer 5: Phase smoke test — c_v positive, finite in both phases.
    # ───────────────────────────────────────────────────────────────────────
    @testset "phase smoke test: c_v positive & finite" begin
        m_gapless = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
        m_gapped = KitaevHoneycomb(; Kx=0.5, Ky=0.5, Kz=2.0)
        for β in (0.5, 1.0, 2.0)
            for m in (m_gapless, m_gapped)
                c_inf = QAtlas.fetch(m, SpecificHeat(), Infinite(); beta=β)
                @test isfinite(c_inf)
                @test c_inf > 0
                c_obc = QAtlas.fetch(m, SpecificHeat(), OBC(0); Lx=4, Ly=4, beta=β)
                @test isfinite(c_obc)
                @test c_obc > 0
            end
        end
    end
end
