using QAtlas: KitaevHoneycomb, Energy, MassGap, Infinite, PBC, OBC
using Test

# Reference value taken from Baskaran, Mandal & Shankar (PRL 98, 247201)
# and reproduced in Feng et al. DMRG benchmarks of the Kitaev model:
# at the isotropic point (Kx = Ky = Kz = 1) the ground state energy
# per site for H = -Σ Kγ σγ σγ is
#
#     ε₀ ≈ -0.7872986...
#
# i.e. `-⟨|f(k)|⟩ / 2` in the conventions of the module.

const ε_isotropic_TL = -0.7872986216706852

@testset "KitaevHoneycomb: TL isotropic matches -<|f|>/2" begin
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    E = QAtlas.fetch(m, Energy(), Infinite())
    @test E ≈ ε_isotropic_TL rtol = 1e-6
end

@testset "KitaevHoneycomb: PBC → TL extrapolation (Kx=Ky=Kz=1)" begin
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    E_TL = QAtlas.fetch(m, Energy(), Infinite())
    # Discrete Bloch sum should converge monotonically-ish to E_TL.
    E_pbc = [QAtlas.fetch(m, Energy(), PBC(0); Lx=L, Ly=L) for L in (8, 16, 32)]
    for (L, E) in zip((8, 16, 32), E_pbc)
        @test abs(E - E_TL) < 0.01          # well within 1% of TL
    end
    @test abs(E_pbc[end] - E_TL) < abs(E_pbc[1] - E_TL)   # finite-size shrinks
end

@testset "KitaevHoneycomb: OBC finite values are well-defined and negative" begin
    m = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    # Known reference values from the flux-free-sector ansatz on small
    # Lx × Ly OBC strips (L1·L2 unit cells → 2·L1·L2 sites).
    # These were generated by running the same code — freezing them
    # here protects against accidental regressions.
    @test QAtlas.fetch(m, Energy(), OBC(0); Lx=2, Ly=2) ≈ -0.5832335726130254 rtol = 1e-12
    @test QAtlas.fetch(m, Energy(), OBC(0); Lx=3, Ly=3) ≈ -0.6304009569087188 rtol = 1e-12
end

@testset "KitaevHoneycomb: positivity & monotonicity under coupling scaling" begin
    # Doubling every coupling doubles the ground state energy (H is linear in K).
    m1 = KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0)
    m2 = KitaevHoneycomb(; Kx=2.0, Ky=2.0, Kz=2.0)
    E1 = QAtlas.fetch(m1, Energy(), Infinite())
    E2 = QAtlas.fetch(m2, Energy(), Infinite())
    @test E2 ≈ 2 * E1 rtol = 1e-8
end

@testset "KitaevHoneycomb: MassGap follows the phase diagram" begin
    # Isotropic / generic gapless (B-phase): all |Kγ| ≤ sum of the others.
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=1.0, Ky=1.0, Kz=1.0),
        MassGap(), Infinite()) == 0.0
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=0.8, Ky=1.0, Kz=1.1),
        MassGap(), Infinite()) == 0.0

    # Az phase: Kz > Kx + Ky ⇒ Δ = 2·(Kz − Kx − Ky).
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=0.5, Ky=0.5, Kz=2.0),
        MassGap(), Infinite()) ≈ 2.0 rtol = 1e-12

    # Ax phase: Kx > Ky + Kz.
    @test QAtlas.fetch(KitaevHoneycomb(; Kx=2.0, Ky=0.5, Kz=0.5),
        MassGap(), Infinite()) ≈ 2.0 rtol = 1e-12
end

@testset "KitaevHoneycomb: OBC argument validation" begin
    m = KitaevHoneycomb()
    @test_throws ErrorException QAtlas.fetch(m, Energy(), OBC(0); Lx=0, Ly=4)
    @test_throws ErrorException QAtlas.fetch(m, Energy(), PBC(0); Lx=4, Ly=0)
end
