# ─────────────────────────────────────────────────────────────────────────────
# Kitaev honeycomb model — finite-temperature thermodynamics in the
# flux-free / matter-Majorana sector.
#
# **Physical scope.**  The exact Kitaev sector decomposition factorises the
# spin Hilbert space into a Z₂ flux sector × matter Majorana sector.  Lieb's
# theorem fixes the ground state in the all-plaquettes-positive flux sector
# and, in that sector, the matter Majoranas form a free hopping problem
# whose Bloch Hamiltonian is the same one that produces the T = 0 results
# in `KitaevHoneycomb.jl` (positive band `λ_k = |f(k)|`).
#
# At finite temperature the Z₂ fluxes also fluctuate; their full thermo-
# dynamics requires Monte Carlo / semi-analytic methods (Nasu, Udagawa,
# Motome 2014) and is out of scope here.  This file implements the
# **matter-sector free-fermion approximation**: it computes the free
# fermion partition function generated by the Bogoliubov-de Gennes
# spectrum of the flux-free sector, giving
#
#   Z_matter(β) = ∏_k 2 cosh(β λ_k / 2),
#
# from which all thermodynamic potentials follow as standard derivatives.
# This is **valid below the flux gap T ≪ Δ_v** (Δ_v ≈ 0.07 |K| at the
# isotropic gapless point; larger in the gapped A_γ phases).
#
# Per-site normalisation: there are two sites per honeycomb unit cell, so
# `N_sites = 2 N_cells` and every per-site potential carries an extra
# factor `1/2` relative to the per-mode quantity.
#
# Quantities exposed via `fetch` (per-site native granularity):
#
#   FreeEnergy       f(β)   = -T log Z / N_sites
#   ThermalEntropy   s(β)   = β (ε - f)
#   SpecificHeat     c_v(β) = ∂ε/∂T
#   Energy{:per_site} ε(β)  generalised: `beta` kwarg optional.  Without
#                            `beta` returns the existing T = 0 ground-state
#                            energy (back-compat).  With `beta::Real`
#                            returns the matter-sector thermal value.
#
# Magnetisation / susceptibility are *not* implemented: σᵅᵢ flips two
# adjacent plaquette fluxes, so ⟨σᵅᵢ⟩ vanishes identically in the
# flux-free sector and the matter-sector approximation gives no useful
# information about them.  Tracking those observables requires a full
# flux-sector ensemble; left for a follow-up issue.
#
# References
#   - A. Kitaev, "Anyons in an exactly solved model and beyond",
#     Ann. Phys. 321, 2 (2006).
#   - E. H. Lieb, PRL 73, 2158 (1994) — flux-free ground state.
#   - J. Nasu, M. Udagawa, Y. Motome, PRL 113, 197205 (2014) — full
#     finite-T thermodynamics including flux fluctuations.
# ─────────────────────────────────────────────────────────────────────────────

using LinearAlgebra: svdvals
using QuadGK: quadgk

# ═══════════════════════════════════════════════════════════════════════════════
# Internal: numerically stable `log(2 cosh(x))`
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _kitaev_logcosh2(x) -> typeof(x)

Numerically stable evaluation of `log(2 cosh(x)) = |x| + log1p(exp(-2|x|))`.
The naive `log(2 cosh(x))` overflows for `|x| ≳ 700`; this rewriting is
exact and stays bounded (`→ |x|`) at large arguments.

Named with a `_kitaev_` prefix to avoid shadowing the analogous helper in
`TFIM_thermal.jl` once both files are included in the same module.
"""
@inline function _kitaev_logcosh2(x::Real)
    a = abs(x)
    return a + log1p(exp(-2 * a))
end

# ═══════════════════════════════════════════════════════════════════════════════
# Internal: BZ double-integral helper
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _kitaev_bz_integral(integrand, model; rtol) -> Float64

Adaptive nested Gauss-Kronrod quadrature of `integrand(θ₁, θ₂)` over the
2D Brillouin zone `(θ₁, θ₂) ∈ [0, 2π)²`.  Mirrors the inner / outer
tolerance choice already used by the T = 0 `Energy` integration in
[`KitaevHoneycomb.jl`](@ref).  Returns the integral value (the
contribution of the prefactor `1/((2π)²)` is left to the caller).
"""
function _kitaev_bz_integral(integrand, model::KitaevHoneycomb; rtol::Float64=1e-8)
    inner(θ₁) = first(
        quadgk(θ₂ -> integrand(model, θ₁, θ₂), 0.0, 2π; rtol=rtol * 10, atol=1e-14)
    )
    I, _ = quadgk(inner, 0.0, 2π; rtol=rtol, atol=1e-14)
    return I
end

# ═══════════════════════════════════════════════════════════════════════════════
# Thermodynamic potentials — Infinite (per-site)
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _kitaev_thermo_infinite(quantity, model, β; rtol) -> Float64

Per-site matter-sector thermodynamic potential of the infinite Kitaev
honeycomb at inverse temperature `β`.  `quantity` is one of
`(:free_energy, :entropy, :specific_heat, :energy)`.

The integrals are evaluated via adaptive Gauss-Kronrod quadrature over
the BZ (see [`_kitaev_bz_integral`](@ref)).  The leading factor
`1/(2·(2π)²)` accounts for the per-site (two sublattice atoms) and the
2D BZ volume.
"""
function _kitaev_thermo_infinite(
    quantity::Symbol, model::KitaevHoneycomb, β::Real; rtol::Float64=1e-8
)
    # Single-mode spectrum is ±λ (matter Majorana convention
    # H = i Σ M_αβ c_α c_β; eigenvalues of one f-mode are ±σ_k where
    # σ_k = svdvals(M)). Hence Z_k = 2 cosh(βλ), ⟨H_k⟩ = -λ tanh(βλ),
    # not the (λ/2, βλ/2) form that would apply if H carried an
    # additional 1/2 prefactor.  Matches the GS formula
    # `ε_gs = -(1/(8π²)) ∫ |f| d²θ` already in `KitaevHoneycomb.jl`
    # at β → ∞.
    integrand = if quantity === :free_energy
        # f = -(1/(2β·(2π)²)) ∫ log(2 cosh(βλ)) d²θ
        (m, θ₁, θ₂) -> begin
            λ = _kitaev_fk_abs(m, θ₁, θ₂)
            _kitaev_logcosh2(β * λ)
        end
    elseif quantity === :entropy
        # s = (1/(2·(2π)²)) ∫ [log(2 cosh(βλ)) - βλ tanh(βλ)] d²θ
        (m, θ₁, θ₂) -> begin
            λ = _kitaev_fk_abs(m, θ₁, θ₂)
            x = β * λ
            _kitaev_logcosh2(x) - x * tanh(x)
        end
    elseif quantity === :specific_heat
        # c_v = (1/(2·(2π)²)) ∫ (βλ)² sech²(βλ) d²θ
        (m, θ₁, θ₂) -> begin
            λ = _kitaev_fk_abs(m, θ₁, θ₂)
            x = β * λ
            x^2 * sech(x)^2
        end
    elseif quantity === :energy
        # ε = -(1/(2·(2π)²)) ∫ λ tanh(βλ) d²θ
        (m, θ₁, θ₂) -> begin
            λ = _kitaev_fk_abs(m, θ₁, θ₂)
            λ * tanh(β * λ)
        end
    else
        error("Unknown Kitaev thermal quantity: $quantity")
    end

    val = _kitaev_bz_integral(integrand, model; rtol=rtol)

    # Per-site = (1/2) · (1/(2π)²) · ∫ ...
    if quantity === :free_energy
        return -val / (2 * β * (2π)^2)
    elseif quantity === :energy
        return -val / (2 * (2π)^2)
    else  # entropy, specific_heat
        return val / (2 * (2π)^2)
    end
end

# ═══════════════════════════════════════════════════════════════════════════════
# Thermodynamic potentials — OBC finite (per-site)
# ═══════════════════════════════════════════════════════════════════════════════

"""
    _kitaev_thermo_obc(quantity, model, Lx, Ly, β) -> Float64

Per-site matter-sector thermodynamic potential of the `Lx × Ly` OBC
honeycomb strip at inverse temperature `β`, computed by summing each BdG
positive Majorana mode's contribution.

The bipartite hopping matrix `M = _obc_hopping_matrix(model, Lx, Ly)` has
`Lx·Ly` positive singular values `σ_k`; the lattice carries
`N_sites = 2·Lx·Ly` sites, so per-site potentials scale as
`(1/(2·Lx·Ly)) Σ_k g(σ_k)` with `g` the free-fermion-mode kernel.
"""
function _kitaev_thermo_obc(
    quantity::Symbol, model::KitaevHoneycomb, Lx::Integer, Ly::Integer, β::Real
)
    # Single-mode spectrum ±σ_k: see the comment block in
    # `_kitaev_thermo_infinite` above.
    M = _obc_hopping_matrix(model, Lx, Ly)
    σ = svdvals(M)
    N_sites = 2 * Lx * Ly
    if quantity === :free_energy
        # f = -(1/(N_sites · β)) Σ log(2 cosh(βσ_k))
        return -sum(s -> _kitaev_logcosh2(β * s), σ) / (N_sites * β)
    elseif quantity === :entropy
        return sum(σ) do s
            x = β * s
            _kitaev_logcosh2(x) - x * tanh(x)
        end / N_sites
    elseif quantity === :specific_heat
        return sum(s -> begin
            x = β * s
            x^2 * sech(x)^2
        end, σ) / N_sites
    elseif quantity === :energy
        # ε = -(1/N_sites) Σ_k σ_k tanh(βσ_k)
        return -sum(s -> s * tanh(β * s), σ) / N_sites
    else
        error("Unknown Kitaev thermal quantity: $quantity")
    end
end

# ═══════════════════════════════════════════════════════════════════════════════
# fetch dispatch — Energy{:per_site} (back-compat extension)
# ═══════════════════════════════════════════════════════════════════════════════
#
# The original GS-only methods on `Energy{:per_site}` live in
# `KitaevHoneycomb.jl`; we cannot redefine them without overwriting.
# Instead we dispatch the *thermal* path on the explicit presence of the
# `beta` kwarg by introducing methods that accept `beta::Real` as a
# *positional-via-kwarg* dispatch, gated through a kwarg shim.

"""
    fetch(model::KitaevHoneycomb, ::Energy{:per_site}, ::Infinite;
          beta=nothing, rtol=1e-8, kwargs...) -> Float64

Per-site **matter-sector energy** of the infinite Kitaev honeycomb.

- `beta = nothing` (default) routes to the existing T = 0 ground-state
  formula `ε_gs = -(1/(8π²)) ∫ |f| d²θ` — preserved bit-for-bit (the
  method dispatched is the original one in `KitaevHoneycomb.jl`).
- `beta::Real` returns the finite-temperature value
  `ε(β) = -(1/(2·(2π)²)) ∫ (λ/2) tanh(βλ/2) d²θ` in the
  matter-sector free-fermion approximation.

Approximation regime: valid for `T ≪ Δ_v` (flux gap; `Δ_v ≈ 0.07|K|` at
the isotropic gapless point).  Above the flux gap the full
finite-temperature thermodynamics needs flux-sector Monte Carlo (Nasu
et al. 2014).
"""
function _kitaev_energy_per_site_infinite_thermal(
    model::KitaevHoneycomb, β::Real; rtol::Float64=1e-8
)
    return _kitaev_thermo_infinite(:energy, model, β; rtol=rtol)
end

"""
    fetch(model::KitaevHoneycomb, ::Energy{:per_site}, ::OBC;
          Lx, Ly, beta=nothing) -> Float64

Per-site **matter-sector energy** on a `Lx × Ly` OBC honeycomb strip.

- `beta = nothing` (default) returns the T = 0 ground-state energy
  `-Σ σ_k / (2·Lx·Ly)` already provided by `KitaevHoneycomb.jl` — the
  original method is preserved unchanged.
- `beta::Real` returns the matter-sector thermal value
  `ε(β) = -(1/(2·Lx·Ly)) Σ_k (σ_k/2) tanh(βσ_k/2)`.

Same matter-sector approximation regime as the `Infinite` variant.
"""
function _kitaev_energy_per_site_obc_thermal(
    model::KitaevHoneycomb, Lx::Integer, Ly::Integer, β::Real
)
    return _kitaev_thermo_obc(:energy, model, Lx, Ly, β)
end

# Concrete `Energy{:per_site}` thermal methods.  Dispatching on the
# kwarg is done via a thin pass-through method whose `beta` default
# matches the original signature: `beta=nothing` falls back to GS.
#
# Important: the original GS-only methods in `KitaevHoneycomb.jl` already
# match `fetch(::KitaevHoneycomb, ::Energy{:per_site}, ::Infinite; ...)`,
# so we *replace* them here with a unified version that branches on
# `beta`.  Because both files are loaded into the same module, the later
# include of this `_thermal.jl` overrides the earlier method — the GS
# behaviour is preserved bit-for-bit when `beta === nothing`.

function fetch(
    model::KitaevHoneycomb,
    ::Energy{:per_site},
    ::Infinite;
    beta=nothing,
    rtol::Float64=1e-8,
    kwargs...,
)
    if beta === nothing
        # T = 0 GS path: ε_gs = -(1/(8π²)) ∫ |f| d²θ.
        inner(θ₁) = first(
            quadgk(
                θ₂ -> _kitaev_fk_abs(model, θ₁, θ₂),
                0.0,
                2π;
                rtol=rtol * 10,
                atol=1e-14,
            )
        )
        I, _ = quadgk(inner, 0.0, 2π; rtol=rtol, atol=1e-14)
        return -I / (8π^2)
    else
        return _kitaev_energy_per_site_infinite_thermal(model, beta; rtol=rtol)
    end
end

function fetch(
    model::KitaevHoneycomb,
    ::Energy{:per_site},
    ::OBC;
    Lx::Integer,
    Ly::Integer,
    beta=nothing,
    kwargs...,
)
    Lx > 0 && Ly > 0 ||
        error("KitaevHoneycomb OBC: Lx, Ly must be positive (got Lx=$Lx, Ly=$Ly).")
    if beta === nothing
        M = _obc_hopping_matrix(model, Lx, Ly)
        σ = svdvals(M)
        return -sum(σ) / (2 * Lx * Ly)
    else
        return _kitaev_energy_per_site_obc_thermal(model, Lx, Ly, beta)
    end
end

# ═══════════════════════════════════════════════════════════════════════════════
# fetch dispatch — FreeEnergy / ThermalEntropy / SpecificHeat
# ═══════════════════════════════════════════════════════════════════════════════
#
# Mirrors `_TFIM_THERMAL_METHODS` table in `TFIM_thermal.jl`.

const _KITAEV_THERMAL_METHODS = (
    (FreeEnergy, :free_energy),
    (ThermalEntropy, :entropy),
    (SpecificHeat, :specific_heat),
)

for (QTy, qsym) in _KITAEV_THERMAL_METHODS
    @eval begin
        """
            fetch(model::KitaevHoneycomb, ::$($QTy), ::Infinite;
                  beta::Real, rtol=1e-8, kwargs...)

        Per-site $($(string(qsym))) of the infinite Kitaev honeycomb at
        inverse temperature `beta`, in the matter-sector free-fermion
        approximation (valid for `T ≪ Δ_v`; see module header).  Adaptive
        2D Gauss-Kronrod quadrature over the BZ.
        """
        function fetch(
            model::KitaevHoneycomb,
            ::$QTy,
            ::Infinite;
            beta::Real,
            rtol::Float64=1e-8,
            kwargs...,
        )
            return _kitaev_thermo_infinite(
                $(QuoteNode(qsym)), model, beta; rtol=rtol
            )
        end

        """
            fetch(model::KitaevHoneycomb, ::$($QTy), ::OBC;
                  Lx, Ly, beta::Real, kwargs...)

        Per-site $($(string(qsym))) of an `Lx × Ly` OBC Kitaev strip at
        inverse temperature `beta`, in the matter-sector free-fermion
        approximation.  Computed by summing the contribution of each
        Majorana singular value.
        """
        function fetch(
            model::KitaevHoneycomb,
            ::$QTy,
            ::OBC;
            Lx::Integer,
            Ly::Integer,
            beta::Real,
            kwargs...,
        )
            Lx > 0 && Ly > 0 || error(
                "KitaevHoneycomb OBC: Lx, Ly must be positive (got Lx=$Lx, Ly=$Ly).",
            )
            return _kitaev_thermo_obc(
                $(QuoteNode(qsym)), model, Lx, Ly, beta
            )
        end
    end
end
